//Logout


POST http://localhost:5000/api/auth/logout 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0MDc0NzY0NywiZXhwIjoxNzQwNzUxMjQ3fQ._8xNmd5dxMtrFT2GGugCi2xVnTO6f_kuBHT4IKVptfM
X-CSRF-Token: 5ZzLh4Rb-GcpvClugMkJRybZXzOs7OP4tmlU